function renderStudent(){
  const s=getSession(),db=loadDB();if(!s||s.role!=="student")return renderLogin();
  const results=db.results.filter(r=>r.studentId===s.id),submitted=db.submissions.filter(x=>x.studentId===s.id);
  document.getElementById("app").innerHTML=`${header("Typo Skills • Student")}<main class="container">
    <section class="hero student-hero"><div><span class="eyebrow">STUDENT DASHBOARD</span><h1>Welcome, ${esc(s.name)}</h1><p>SKANS ID: <strong>${esc(s.id)}</strong></p></div><div class="student-avatar">${initials(s.name)}</div></section>
    <div class="student-info-grid"><div class="info-card accent"><span>Tests Attempted</span><strong>${submitted.length}</strong></div><div class="info-card"><span>Published Results</span><strong>${results.length}</strong></div><div class="info-card"><span>Test Access</span><strong>Code Required</strong></div></div>
    <section class="card student-start"><div class="section-icon">T</div><div class="start-content"><span class="eyebrow">TEST ACCESS</span><h2>Enter Your Test Code</h2><p class="muted">Your teacher will give you the code for the test you need to take. Other tests are not listed or shown here.</p><div class="code-input-row"><input id="accessCode" maxlength="12" placeholder="Enter test code" autocomplete="off" onkeydown="if(event.key==='Enter')startByCode()"><button class="btn primary" onclick="startByCode()">Open Test</button></div><div id="studentNotice"></div></div></section>
    <section class="section-block"><div class="section-head"><div><span class="eyebrow">RESULTS</span><h2>My Results</h2><p class="muted">Only results published by the administrator appear here.</p></div></div><div class="list">${results.length?results.map(r=>`<div class="list-item"><div><strong>${esc(r.testTitle)}</strong><span class="muted">Published ${new Date(r.publishedAt).toLocaleString()}</span></div><div class="actions"><span class="badge">${r.obtained}/${r.total} • ${r.percentage}%</span><button class="btn secondary" onclick="showStudentResult('${r.id}')">View Result</button></div></div>`).join(""):`<div class="empty"><strong>No published results yet</strong><span>Your results will appear here after the administrator publishes them.</span></div>`}</div></section>
    <section class="danger-zone"><div><span class="eyebrow danger-text">DANGER ZONE</span><h2>Delete My Account</h2><p class="muted">This permanently removes your account, attempts, submissions, results and reset permission from this device.</p></div><button class="btn danger" onclick="deleteMyStudentAccount()">Delete My Account</button></section>
  </main>`;
}
function startByCode(){
  const code=document.getElementById("accessCode").value.trim(),box=document.getElementById("studentNotice"),s=getSession(),db=loadDB();if(!code){box.innerHTML=`<div class="notice error">Please enter the test code given by your teacher.</div>`;return;}
  const t=db.tests.find(x=>x.code.toLowerCase()===code.toLowerCase());if(!t){box.innerHTML=`<div class="notice error">Test code not found. Please check the code with your teacher.</div>`;return;}
  if(db.submissions.some(x=>x.testId===t.id&&x.studentId===s.id)){box.innerHTML=`<div class="notice error">You have already submitted this test.</div>`;return;}
  startTest(t.id);
}
async function deleteMyStudentAccount(){
  const s=getSession();if(!s||s.role!=="student")return;if(!confirm("Delete your account permanently? Your attempts, submissions and results will also be deleted."))return;const db=loadDB(),ids=new Set(db.submissions.filter(x=>x.studentId===s.id).map(x=>x.id));db.users=db.users.filter(u=>u.id!==s.id);db.submissions=db.submissions.filter(x=>x.studentId!==s.id);db.results=db.results.filter(r=>r.studentId!==s.id&&!ids.has(r.submissionId));saveDB(db);clearSession();alert("Your account and related data were deleted.");renderLogin();
}
function showStudentResult(rid){
  const r=loadDB().results.find(x=>x.id===rid);if(!r)return;document.getElementById("app").innerHTML=`${header("Typo Skills • Result")}<main class="container"><div class="page-title"><span class="eyebrow">PUBLISHED RESULT</span><h1>${esc(r.testTitle)}</h1><p class="muted">Result for ${esc(r.studentName)}</p></div><div class="result-box"><div class="result-stat"><span>Obtained</span><b>${r.obtained}</b></div><div class="result-stat"><span>Total</span><b>${r.total}</b></div><div class="result-stat"><span>Percentage</span><b>${r.percentage}%</b></div></div><div class="list">${r.answers.map((a,i)=>`<div class="card"><div class="badge">Question ${i+1} • ${a.awarded}/${a.marks}</div><h3>${esc(a.prompt).replace(/\n/g,"<br>")}</h3><p class="answer-preview">${esc(a.answer)||"<span class='muted'>No answer</span>"}</p>${a.feedback?`<div class="notice info"><b>Feedback:</b> ${esc(a.feedback)}</div>`:""}</div>`).join("")}</div><button class="btn secondary back-button" onclick="renderStudent()">Back to Dashboard</button></main>`;
}
